---
title: "Quiz 4"
author: "George Papadopoulos </br> pgeorgios8@gmail.com"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: leonids
    highlight: github
---
<style>body{text-align: justify}</style>

## Question 1

A pharmaceutical company is interested in testing a potential blood pressure lowering medication. Their first examination
considers only subjects that received the medication at baseline then two weeks later. The data are as follows (SBP in
mmHg)

|Subject|Baseline|Week 2|
|:------|:-------|:-----|
|1	    |140     |132   |
|2      |138     |135   |
|3	    |150	   |151   |
|4	    |148     |146   |
|5	    |135	   |130   |

Consider testing the hypothesis that there was a mean reduction in blood pressure? Give the P-value for the associated
two sided T test. 

<u>answer</u>

We will consider the obervations for each subject as paired.

```{r a1,comment=''}
bl <- c(140, 138, 150, 148, 135)
fu <- c(132, 135, 151, 146, 130)
t.test(fu, bl, alternative = "two.sided", paired = TRUE)
```

$\mathcal{H}_{0}:\mu=0$ vs $\mathcal{H}_{a}:\mu\neq0$, since the p-value is greater than 0.05 we fail to reject the 
null hypothesis.

## Question 2

A sample of 9 men yielded a sample average brain volume of 1,100cc and a standard deviation of 30cc. What is the
complete set of values of $\mu_0$​ that a test of $\mathcal{H}_{0}:\mu=\mu_{0}$ would fail to reject the null
hypothesis in a two sided 5% Students t-test?

<u>answer</u>



## Question 3

Researchers conducted a blind taste test of Coke versus Pepsi. Each of four people was asked which of two blinded
drinks given in random order that they preferred. The data was such that 3 of the 4 people chose Coke. Assuming that
this sample is representative, report a P-value for a test of the hypothesis that Coke is preferred to Pepsi using a
one sided exact test.

<u>answer</u>

