---
title: "Q2"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
knitr::opts_chunk$set(echo = FALSE)
```

### 1.

```{r q1}
question("Who created Markdown?",
  answer("Robert Gentleman"),
  answer("John Gruber",correct = TRUE),
  answer("Hadley Wickham"),
  answer("Yihui Xie"))
```

### 2.

```{r q2}
question('When writing a document in R Markdown, how do you denote the
         beginning of an R code chunk?',
  answer("\t ```"),
  answer('\t <code>'),
  answer('\t ```{r}',correct = TRUE),
  answer('\t <rcode>'))
```

### 3.

```{r q3}
question("When using knitr, how do you indicate the height and width of a plot
         created in a code chunk?",
  answer("Set the 'dpi' option for the code chunk"),
  answer("Set the 'fig.height' and 'fig.width' options for the code
         chunk",correct = TRUE),
  answer("Set the 'size' and 'scale' options for the code chunk"),
  answer("Set the 'height' and 'width' options for the code chunk"))
```

### 4.

```{r q4}
question("With some code chunks, we may not want the output generated by the
         chunk to be rendered into HTML but would prefer to print the output
         verbatim. How can we specify this preference for a given code chunk?",
  answer("Set the option tidy = FALSE"),
  answer("Set the option message = FALSE"),
  answer("Set the option highlight = TRUE"),
  answer("Set the option results = 'asis'",correct = TRUE))
```

### 5.

```{r q5}
question("When using knitr and R Markdown and producing output in HTML, why
         should you never edit the resulting HTML file?",
  answer("Every time you knit() the R Markdown file, the HTML file will be
         overwritten",correct = TRUE),
  answer("The Markdown file generated by knitr is the appropriate file to
         edit."),
  answer("Editing the HTML file requires knowledge of a separate markup
         language."),
  answer("The HTML file is not a text file."))
```