---
title: "Q1"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
knitr::opts_chunk$set(echo = FALSE)
```
<style>
  body {
    text-align: justify
    }
</style>
### 1.

```{r 1}
question("R was developed by statisticians working at",
  answer("Harvard University"),
  answer("Bell Labs"),
  answer("The University of Auckland",correct = TRUE),
  answer("The University of New South Wales"))
```

### 2.

```{r 2}
question("The definition of free software consists of four freedoms (freedoms 0 through 3).
         Which of the following is NOT one of the freedoms that are part of the definition?
         Select all that apply.",
  answer("The freedom to study how the program works, and adapt it to your needs."),
  answer("The freedom to redistribute copies so you can help your neighbor."),
  answer("The freedom to sell the software for any price.",correct = TRUE),
  answer("The freedom to restrict access to the source code for the software.",correct =
           TRUE),
  answer("The freedom to improve the program, and release your improvements to the public, so
         that the whole community benefits."),
  answer("The freedom to prevent users from using the software for undesirable
         purposes.",correct = TRUE),
  answer("The freedom to run the program, for any purpose."))
```


### 3.

```{r 3}
question("In R the following are all atomic data types EXCEPT: (Select all that apply)",
  answer("numeric"),
  answer("table",correct = TRUE),
  answer("array",correct = TRUE),
  answer("matrix",correct = TRUE),
  answer("integer"),
  answer("complex"),
  answer("logical"),
  answer("list",correct = TRUE),
  answer("character"),
  answer("data frame",correct = TRUE))
```

### 4.

```{r 4}
question("If I execute the expression x <- 4L in R, what is the class of the object 'x' as
         determined by the 'class()' function?",
  answer("character"),
  answer("integer",correct = TRUE),
  answer("numeric"),
  answer("matrix"),
  answer("complex"),
  answer("logical"))
```

### 5.

```{r 5}
question("What is the class of the object defined by the expression x <- c(4,'a',TRUE)?",
  answer('mixed'),
  answer('integer'),
  answer('logical'),
  answer('numeric'),
  answer('character',correct = TRUE))
```

### 6.

```{r 6}
question("If I have two vectors x <- c(1,3,5) and y <- c(3,2,10), what is produced by the
         expression rbind(x, y)?",
  answer('a 2 by 2 matrix'),
  answer("a vector of length 3"),
  answer("a matrix with two rows and three columns",correct = TRUE),
  answer("a vector of length 2"),
  answer("a 3 by 2 matrix"),
  answer("a 3 by 3 matrix"))
```

### 7.

```{r 7}
question("A key property of vectors in R is ",
  answer("elements of a vector can only be character or numeric"),
  answer("elements of a vector can be of different classes"),
  answer("a vector cannot have have attributes like dimensions"),
  answer("elements of a vector all must be of the same class",correct = TRUE),
  answer("the length of a vector must be less than 32,768"))
```

### 8.

```{r 8}
question("Suppose I have a list defined as x <- list(2,'a','b', TRUE). What does x[[2]] give
         me? Select all that apply.",
  answer("a list containing a character vector with the elements 'a' and 'b'."),
  answer("a list containing character vector with the letter 'a'."),
  answer("a character vector with the elements 'a' and 'b'."),
  answer("a character vector of length 1.",correct = TRUE),
  answer("a character vector containing letter 'a'.",correct = TRUE))
```

### 9.

```{r 9}
question("Suppose I have a vector x <- 1:4 and a vector y <- 2. What is produced by the
         expression x + y?",
  answer("a numeric vector with elements 3, 4, 5, 6.",correct = TRUE),
  answer("a numeric vector with elements 3, 2, 3, 6."),
  answer("an integer vector with elements 3, 2, 3, 4."),
  answer("a numeric vector with elements 3, 2, 3, 4."),
  answer("a numeric vector with elements 1, 2, 3, 6."),
  answer("an integer vector with elements 3, 2, 3, 6."))
```

### 10.

```{r 10}
question("Suppose I have a vector x <- c(3, 5, 1, 10, 12, 6) and I want to set all elements
         of this vector that are less than 6 to be equal to zero. What R code achieves this?
         Select all that apply.",
  answer("x[x == 6] <- 0"),
  answer("x[x <= 5] <- 0",correct = TRUE),
  answer("x[x == 0] <- 6"),
  answer("x[x < 6] == 0"),
  answer("x[x %in% 1:5] <- 0",correct = TRUE),
  answer("x[x > 0] <- 6"),
  answer("x[x > 6] <- 0"),
  answer("x[x != 6] <- 0"),
  answer("x[x < 6] <- 0",correct = TRUE),
  answer("x[x >= 6] <- 0"),
  answer("x[x == 0] < 6"))
```


Use the [Week 1 Quiz Data Set](https://d396qusza40orc.cloudfront.net/rprog/data/quiz1_data.zip) to answer questions 11-20.

### 11.

```{r 11}
question("In the dataset provided for this Quiz, what are the column names of the dataset?",
  answer("1, 2, 3, 4, 5, 6"),
  answer("Ozone, Solar.R, Wind, Temp, Month, Day",correct = TRUE),
  answer("Ozone, Solar.R, Wind"),
  answer("Month, Day, Temp, Wind")
)
```

<u>answer</u>

```{r answer11,eval = FALSE,echo = TRUE}
library(readr)
download.file("https://d396qusza40orc.cloudfront.net/rprog/data/quiz1_data.zip","data.zip")
unzip("data.zip")
data <- read_csv('hw1_data.csv')
names(data)
```

### 12.

```{r 12}
question("Extract the first 2 rows of the data frame and print them to the console. What does
         the output look like?",
  answer("<pre>  
  Ozone Solar.R Wind Temp Month Day
1     7      NA     6.9  74   5  11
2    35     274     10.3 82   7  17
</pre>"),
  answer("<pre>
  Ozone Solar.R Wind Temp Month Day
1     9      24 10.9   71     9  14
2    18     131  8.0   76     9  29
</pre>"),
  answer("<pre>
  Ozone Solar.R Wind Temp Month Day
1    41     190  7.4   67     5   1
2    36     118  8.0   72     5   2
</pre>",correct = TRUE),
  answer("<pre>
  Ozone Solar.R Wind Temp Month Day
1    18     224 13.8   67     9  17
2    NA     258  9.7   81     7  22
</pre>"))
```

<u>answer</u>

```{r answer12,echo = TRUE,eval = FALSE}
head(data,2)
```

### 13.

```{r 13}
question("How many observations (i.e. rows) are in this data frame?",
  answer("153",correct = TRUE),
  answer("129"),
  answer("45"),
  answer("160"))
```

<u>answer</u>

```{r answer,echo = TRUE,eval = FALSE}
nrow(data)
```

### 14.

```{r 14}
question("Extract the last 2 rows of the data frame and print them to the console. What does
         the output look like?",
  answer("<pre>
    Ozone Solar.R Wind Temp Month Day
152    31     244 10.9   78     8  19
153    29     127  9.7   82     6   7
</pre>"),
  answer("<pre>
     Ozone Solar.R Wind Temp Month Day
152    11      44  9.7   62     5  20
153   108     223  8.0   85     7  25
</pre>"),
  answer("<pre>
    Ozone Solar.R Wind Temp Month Day
152    34     307 12.0   66     5  17
153    13      27 10.3   76     9  18
</pre>"),
answer("<pre>
    Ozone Solar.R Wind Temp Month Day
152    18     131  8.0   76     9  29
153    20     223 11.5   68     9  30
</pre>",correct = TRUE))
```

<u>answer</u>

```{r answer14,echo = TRUE,eval = FALSE}
tail(data,2)
```

### 15.

```{r 15}
question("What is the value of Ozone in the 47th row?",
  answer("18"),
  answer("63"),
  answer("21",correct = TRUE),
  answer("34"))
```

<u>answer</u>

```{r answer15,echo = TRUE,eval = FALSE}
data$Ozone[47]
```

### 16.

```{r 16}
question("How many missing values are in the Ozone column of this data frame?",
  answer("9"),
  answer("43"),
  answer("37",correct = TRUE),
  answer("78"))
```

<u>answer</u>

```{r answer16,echo = TRUE,eval = FALSE}
sum(is.na(data$Ozone))
```

### 17.

```{r 17}
question("What is the mean of the Ozone column in this dataset? Exclude missing values (coded
         as NA) from this calculation.",
  answer("42.1",correct = TRUE),
  answer("18.0"),
  answer("31.5"),
  answer("53.2"))
```

<u>answer</u>

```{r answer17,echo = TRUE,eval = FALSE}
mean(data$Ozone,na.rm = TRUE)
```

### 18.

```{r 18}
question("Extract the subset of rows of the data frame where Ozone values are above 31 and
         Temp values are above 90. What is the mean of Solar.R in this subset?",
  answer("185.9"),
  answer("334.0"),
  answer("205.0"),
  answer("212.8",correct = TRUE))
```

<u>answer</u>

```{r answer18,echo = TRUE,eval = FALSE}
library(dplyr,quietly = TRUE,warn.conflicts = FALSE)
data %>% filter(Ozone > 31 & Temp > 90) %>% summarize(mean(Solar.R))
```


### 19.

```{r 19}
question("What is the mean of 'Temp' when 'Month' is equal to 6?",
  answer("75.3"),
  answer("85.6"),
  answer("79.1",correct = TRUE),
  answer("90.2"))
```

<u>answer</u>

```{r answer19,echo = TRUE,eval = FALSE}
data %>% filter(Month == 6) %>% summarize(mean(Temp))
```

### 20.

```{r 20}
question("What was the maximum ozone value in the month of May (i.e. Month is equal to 5)?",
  answer("100"),
  answer("115",correct = TRUE),
  answer("18"),
  answer("97"))
```

<u>answer</u>

```{r answer20,echo = TRUE,eval = FALSE}
data %>% filter(Month == 5) %>% summarize(max(Ozone,na.rm = TRUE))
```

---